version: 1.0.{build}
platform: x64

clone_folder: c:\gopath\src\github.com\ryosan-470\factordb-go

environment:
  GOPATH: c:\gopath

install:
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t -d ./...

build_script:
  - go build -o factordb.exe
  - go test -v -race ./...

artifacts:
  - path: factordb.exe
    name: binary
